# Generated by Django 4.0.6 on 2022-09-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updeted',
            new_name='updeted_time',
        ),
    ]
