# Generated by Django 4.0.6 on 2022-09-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_rename_created_post_created_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updeted_time',
            new_name='updeted_at',
        ),
    ]
