# Generated by Django 4.0.6 on 2022-09-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_rename_created_time_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['publish_time'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updeted_at',
            new_name='updeted_time',
        ),
        migrations.AddField(
            model_name='post',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
