# Generated by Django 4.0.6 on 2022-09-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0006_remove_comment_created_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updeted_time',
        ),
    ]
