# Generated by Django 4.0.6 on 2022-09-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_remove_post_updeted_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='updeted_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updeted_time'),
        ),
    ]
