# Generated by Django 4.0.6 on 2022-09-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0008_alter_post_options_post_updeted_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Featured',
            field=models.BooleanField(null=True, verbose_name='Featured'),
        ),
    ]
