# Generated by Django 4.0.6 on 2022-09-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0010_post_dislikes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
    ]
